### ISSUE TITLE
404 error on the endpoint POST /decision-definition/key/calc-credit-sum/evaluate

### ISSUE THREAD

**Issue by rrjavadev** [tasso94/camunda-dmn-feel-1.2-example#1]
Hiya,

This is a very good article. When I am trying to follow the readme file by making a POST request to the endpoint 
POST http://localhost:8080/decision-definition/key/calc-credit-sum/evaluate

{
   "variables":{
      "credit_history":{
         "value":" [{\"type\":\"personal-loan\", \"score\": 505, \"granted_sum\": 1554.30}, {\"type\":\"mortgage\", \"score\": 931, \"granted_sum\": 600900.43}, {\"type\":\"mortgage\", \"score\": 754, \"granted_sum\": 210000.00}, {\"type\":\"personal-loan\", \"score\": 437, \"granted_sum\": 1900.44}]",
         "type": "Json"
      },
      "credit_score":{
         "value": 800
      },
      "credit_type":{
         "value": "mortgage"
      }
   }
}

I am getting the following error.
{
    "timestamp": "2021-01-13T13:59:38.543+0000",
    "status": 404,
    "error": "Not Found",
    "message": "No message available",
    "path": "/decision-definition/key/calc-credit-sum/evaluate"
}

I have used both the camunda version specified in the Readme as well as 7.14.0. What could be the problem?

**Comment by tasso94** [comment]
Hi @roshinirevindranathan,

In 7.13.0-alpha2 the endpoint is located under http://localhost:8080/rest/decision-definition/key/calc-credit-sum/evaluate, whereas in 7.14.0, the endpoint is located under http://localhost:8080/engine-rest/decision-definition/key/calc-credit-sum/evaluate 

Best,
Tassilo

**Comment by rrjavadev** [comment]
Thank you. That has worked perfectly for both the versions!
